import { PolyatomicIonData } from "./interfaces";

// Polyatomic anions
export const acidPolyatomicAnions: readonly string[] = ["acetate", "cyanide", "hypobromite", "bromite", "bromate", "perbromate", "hypochlorite", "chlorite", "chlorate", "perchlorate", "hypoiodite", "iodite", "iodate", "periodate", "nitrite", "nitrate", "carbonate", "oxalate", "chromate", "dichromate", "selenite", "selenate", "sulfite", "sulfate", "tellurite", "tellurate", "arsenite", "arsenate", "phosphite", "phosphate"];

// Polyatomic ions
export const polyatomicAnions: readonly string[] = [...acidPolyatomicAnions, "bicarbonate", "permanganate", "hydroxide", "bisulfite", "bisulfate", "thiocyanate", "persulfate"];
export const polyatomicCations: readonly string[] = ["ammonium"];

// Polyatomic ions on solubility table - double replacement reactions
export const drPolyatomicAnions: readonly string[] = ["chlorate", "hydroxide", "sulfite", "sulfate", "carbonate", "nitrite", "nitrate", "phosphate", "acetate", "chromate"];
export const drPolyatomicCations: readonly string[] = ["ammonium"];

export const polyatomicIonData: PolyatomicIonData = {
    ammonium: {
        ionFormula: "NH/4/",
        ionParts: ["NH", 4],
        ionName: "ammonium",
        charge: 1,
        solubilityTable: {
            fluoride: true,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: true,
            sulfite: true,
            sulfate: true,
            carbonate: true,
            nitrite: true,
            nitrate: true,
            phosphate: true,
            acetate: true,
            chromate: true,
        },
        molarMass: 18.04,
    },
    acetate: {
        ionFormula: "CH/3/COO",
        ionParts: ["CH", 3, "COO"],
        ionName: "acetate",
        charge: -1,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: true,
            barium: true,
            iron: true,
            copper: true,
            silver: false,
            zinc: true,
            lead: true,
            aluminum: false,
            mercury: false,
        },
        molarMass: 59.04,
    },
    cyanide: {
        ionFormula: "CN",
        ionParts: ["CN"],
        ionName: "cyanide",
        charge: -1,
        molarMass: 26.02,
    },
    bicarbonate: {
        ionFormula: "HCO/3/",
        ionParts: ["HCO", 3],
        ionName: "bicarbonate",
        charge: -1,
        molarMass: 61.02,
    },
    hypobromite: {
        ionFormula: "BrO",
        ionParts: ["BrO"],
        ionName: "hypobromite",
        charge: -1,
        molarMass: 95.90,
    },
    bromite: {
        ionFormula: "BrO/2/",
        ionParts: ["BrO", 2],
        ionName: "bromite",
        charge: -1,
        molarMass: 111.90,
    },
    bromate: {
        ionFormula: "BrO/3/",
        ionParts: ["BrO", 3],
        ionName: "bromate",
        charge: -1,
        molarMass: 127.90,
    },
    perbromate: {
        ionFormula: "BrO/4/",
        ionParts: ["BrO", 4],
        ionName: "perbromate",
        charge: -1,
        molarMass: 143.90,
    },
    hypochlorite: {
        ionFormula: "ClO",
        ionParts: ["ClO"],
        ionName: "hypochlorite",
        charge: -1,
        molarMass: 51.45,
    },
    chlorite: {
        ionFormula: "ClO/2/",
        ionParts: ["ClO", 2],
        ionName: "chlorite",
        charge: -1,
        molarMass: 67.45,
    },
    chlorate: {
        ionFormula: "ClO/3/",
        ionParts: ["ClO", 3],
        ionName: "chlorate",
        charge: -1,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: true,
            barium: true,
            iron: true,
            copper: true,
            silver: true,
            zinc: true,
            lead: true,
            aluminum: true,
            mercury: false,
        },
        molarMass: 83.45,
    },
    perchlorate: {
        ionFormula: "ClO/4/",
        ionParts: ["ClO", 4],
        ionName: "perchlorate",
        charge: -1,
        molarMass: 99.45,
    },
    hypoiodite: {
        ionFormula: "IO",
        ionParts: ["IO"],
        ionName: "hypoiodite",
        charge: -1,
        molarMass: 142.90,
    },
    iodite: {
        ionFormula: "IO/2/",
        ionParts: ["IO", 2],
        ionName: "iodite",
        charge: -1,
        molarMass: 158.90,
    },
    iodate: {
        ionFormula: "IO/3/",
        ionParts: ["IO", 3],
        ionName: "iodate",
        charge: -1,
        molarMass: 174.90,
    },
    periodate: {
        ionFormula: "IO/4/",
        ionParts: ["IO", 4],
        ionName: "periodate",
        charge: -1,
        molarMass: 190.90,
    },
    permanganate: {
        ionFormula: "MnO/4/",
        ionParts: ["MnO", 4],
        ionName: "permanganate",
        charge: -1,
        molarMass: 118.94,
    },
    nitrite: {
        ionFormula: "NO/2/",
        ionParts: ["NO", 2],
        ionName: "nitrite",
        charge: -1,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: true,
            barium: true,
            iron: true,
            copper: true,
            silver: false,
            zinc: true,
            lead: true,
            aluminum: true,
            mercury: true,
        },
        molarMass: 46.01,
    },
    nitrate: {
        ionFormula: "NO/3/",
        ionParts: ["NO", 3],
        ionName: "nitrate",
        charge: -1,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: true,
            barium: true,
            iron: true,
            copper: true,
            silver: true,
            zinc: true,
            lead: true,
            aluminum: true,
            mercury: true,
        },
        molarMass: 46.01,
    },
    hydroxide: {
        ionFormula: "OH",
        ionParts: ["OH"],
        ionName: "hydroxide",
        charge: -1,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: false,
            calcium: false,
            barium: true,
            iron: false,
            copper: false,
            silver: false,
            zinc: false,
            lead: false,
            aluminum: false,
            mercury: false,
        },
        molarMass: 17.01,
    },
    bisulfite: {
        ionFormula: "HSO/3/",
        ionParts: ["HSO", 3],
        ionName: "bisulfite",
        charge: -1,
        molarMass: 81.08,
    },
    bisulfate: {
        ionFormula: "HSO/4/",
        ionParts: ["HSO", 4],
        ionName: "bisulfate",
        charge: -1,
        molarMass: 97.08,
    },
    thiocyanate: {
        ionFormula: "SCN",
        ionParts: ["SCN"],
        ionName: "thiocyanate",
        charge: -1,
        molarMass: 58.09,
    },
    carbonate: {
        ionFormula: "CO/3/",
        ionParts: ["CO", 3],
        ionName: "carbonate",
        charge: -2,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: false,
            calcium: false,
            barium: false,
            iron: false,
            copper: false,
            silver: false,
            zinc: false,
            lead: false,
            aluminum: true,
            mercury: false,
        },
        molarMass: 60.01,
    },
    oxalate: {
        ionFormula: "C/2/O/4/",
        ionParts: ["C", 2, "O", 4],
        ionName: "oxalate",
        charge: -2,
        molarMass: 88.02,
    },
    chromate: {
        ionFormula: "CrO/4/",
        ionParts: ["CrO", 4],
        ionName: "chromate",
        charge: -2,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: true,
            barium: false,
            iron: false,
            copper: false,
            silver: false,
            zinc: true,
            lead: false,
            aluminum: false,
            mercury: false,
        },
        molarMass: 116.00,
    },
    dichromate: {
        ionFormula: "Cr/2/O/7/",
        ionParts: ["Cr", 2, "O", 7],
        ionName: "dichromate",
        charge: -2,
        molarMass: 216.00,
    },
    selenite: {
        ionFormula: "SeO/3/",
        ionParts: ["SeO", 3],
        ionName: "selenite",
        charge: -2,
        molarMass: 126.97,
    },
    selenate: {
        ionFormula: "SeO/4/",
        ionParts: ["SeO", 4],
        ionName: "selenate",
        charge: -2,
        molarMass: 142.97,
    },
    sulfite: {
        ionFormula: "SO/3/",
        ionParts: ["SO", 3],
        ionName: "sulfite",
        charge: -2,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: false,
            barium: false,
            iron: true,
            copper: true,
            silver: false,
            zinc: false,
            lead: false,
            aluminum: true,
            mercury: false,
        },
        molarMass: 80.07,
    },
    sulfate: {
        ionFormula: "SO/4/",
        ionParts: ["SO", 4],
        ionName: "sulfate",
        charge: -2,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: false,
            barium: false,
            iron: true,
            copper: true,
            silver: false,
            zinc: true,
            lead: false,
            aluminum: true,
            mercury: false,
        },
        molarMass: 96.07,
    },
    persulfate: {
        ionFormula: "SO/5/",
        ionParts: ["SO", 5],
        ionName: "persulfate",
        charge: -2,
        molarMass: 112.07,
    },
    tellurite: {
        ionFormula: "TeO/3/",
        ionParts: ["TeO", 3],
        ionName: "tellurite",
        charge: -2,
        molarMass: 175.6,
    },
    tellurate: {
        ionFormula: "TeO/4/",
        ionParts: ["TeO", 4],
        ionName: "tellurate",
        charge: -2,
        molarMass: 191.6,
    },
    arsenite: {
        ionFormula: "AsO/3/",
        ionParts: ["AsO", 3],
        ionName: "arsenite",
        charge: -3,
        molarMass: 122.92,
    },
    arsenate: {
        ionFormula: "AsO/4/",
        ionParts: ["AsO", 4],
        ionName: "arsenate",
        charge: -3,
        molarMass: 138.92,
    },
    phosphite: {
        ionFormula: "PO/3/",
        ionParts: ["PO", 3],
        ionName: "phosphite",
        charge: -3,
        molarMass: 78.97,
    },
    phosphate: {
        ionFormula: "PO/4/",
        ionParts: ["PO", 4],
        ionName: "phosphate",
        charge: -3,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: false,
            sodium: true,
            potassium: true,
            magnesium: false,
            calcium: false,
            barium: false,
            iron: false,
            copper: false,
            silver: false,
            zinc: false,
            lead: false,
            aluminum: false,
            mercury: false,
        },
        molarMass: 94.97,
    },
}