import { PolyatomicIonData } from "./interfaces";

// Polyatomic anions
export const acidPolyatomicAnions: readonly string[] = ["acetate", "cyanide", "hypobromite", "bromite", "bromate", "perbromate", "hypochlorite", "chlorite", "chlorate", "perchlorate", "hypoiodite", "iodite", "iodate", "periodate", "nitrite", "nitrate", "carbonate", "oxalate", "chromate", "dichromate", "selenite", "selenate", "sulfite", "sulfate", "tellurite", "tellurate", "arsenite", "arsenate", "phosphite", "phosphate"];

// Polyatomic ions
export const polyatomicAnions: readonly string[] = [...acidPolyatomicAnions, "bicarbonate", "permanganate", "hydroxide", "bisulfite", "bisulfate", "thiocyanate", "persulfate"];
export const polyatomicCations: readonly string[] = ["ammonium"];

// Polyatomic ions on solubility table - double replacement reactions
export const drPolyatomicAnions: readonly string[] = ["chlorate", "hydroxide", "sulfite", "sulfate", "carbonate", "nitrite", "nitrate", "phosphate", "acetate", "chromate"];
export const drPolyatomicCations: readonly string[] = ["ammonium"];

export const polyatomicIonData: PolyatomicIonData = {
    ammonium: {
        ionName: "ammonium",
        ionFormula: "NH/4/",
        ionParts: ["NH", 4],
        charge: 1,
        isPolyatomic: true,
        molarMass: 18.04,
        solubilityTable: {
            F: true,
            Cl: true,
            Br: true,
            I: true,
            chlorate: true,
            hydroxide: true,
            sulfite: true,
            sulfate: true,
            carbonate: true,
            nitrite: true,
            nitrate: true,
            phosphate: true,
            acetate: true,
            chromate: true,
        },
        subscript: 1,
    },
    acetate: {
        ionName: "acetate",
        ionFormula: "CH/3/COO",
        ionParts: ["CH", 3, "COO"],
        charge: -1,
        isPolyatomic: true,
        molarMass: 59.04,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: true,
            Ca: true,
            Ba: true,
            Fe: true,
            Cu: true,
            Ag: false,
            Zn: true,
            Pb: true,
            Al: false,
            Hg: false,
        }, 
        subscript: 1,
    },
    cyanide: {
        ionName: "cyanide",
        ionFormula: "CN",
        ionParts: ["CN"],
        charge: -1,
        isPolyatomic: true,
        molarMass: 26.02,
        subscript: 1,
    },
    bicarbonate: {
        ionName: "bicarbonate",
        ionFormula: "HCO/3/",
        ionParts: ["HCO", 3],
        charge: -1,
        isPolyatomic: true,
        molarMass: 61.02,
        subscript: 1,
    },
    hypobromite: {
        ionName: "hypobromite",
        ionFormula: "BrO",
        ionParts: ["BrO"],
        charge: -1,
        isPolyatomic: true,
        molarMass: 95.90,
        subscript: 1,
    },
    bromite: {
        ionName: "bromite",
        ionFormula: "BrO/2/",
        ionParts: ["BrO", 2],
        charge: -1,
        isPolyatomic: true,
        molarMass: 111.90,
        subscript: 1,
    },
    bromate: {
        ionName: "bromate",
        ionFormula: "BrO/3/",
        ionParts: ["BrO", 3],
        charge: -1,
        isPolyatomic: true,
        molarMass: 127.90,
        subscript: 1,
    },
    perbromate: {
        ionName: "perbromate",
        ionFormula: "BrO/4/",
        ionParts: ["BrO", 4],
        charge: -1,
        isPolyatomic: true,
        molarMass: 143.90,
        subscript: 1,
    },
    hypochlorite: {
        ionName: "hypochlorite",
        ionFormula: "ClO",
        ionParts: ["ClO"],
        charge: -1,
        isPolyatomic: true,
        molarMass: 51.45,
        subscript: 1,
    },
    chlorite: {
        ionName: "chlorite",
        ionFormula: "ClO/2/",
        ionParts: ["ClO", 2],
        charge: -1,
        isPolyatomic: true,
        molarMass: 67.45,
        subscript: 1,
    },
    chlorate: {
        ionName: "chlorate",
        ionFormula: "ClO/3/",
        ionParts: ["ClO", 3],
        charge: -1,
        isPolyatomic: true,
        molarMass: 83.45,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: true,
            Ca: true,
            Ba: true,
            Fe: true,
            Cu: true,
            Ag: true,
            Zn: true,
            Pb: true,
            Al: true,
            Hg: false,
        },
        subscript: 1,
    },
    perchlorate: {
        ionName: "perchlorate",
        ionFormula: "ClO/4/",
        ionParts: ["ClO", 4],
        charge: -1,
        isPolyatomic: true,
        molarMass: 99.45,
        subscript: 1,
    },
    hypoiodite: {
        ionName: "hypoiodite",
        ionFormula: "IO",
        ionParts: ["IO"],
        charge: -1,
        isPolyatomic: true,
        molarMass: 142.90,
        subscript: 1,
    },
    iodite: {
        ionName: "iodite",
        ionFormula: "IO/2/",
        ionParts: ["IO", 2],
        charge: -1,
        isPolyatomic: true,
        molarMass: 158.90,
        subscript: 1,
    },
    iodate: {
        ionName: "iodate",
        ionFormula: "IO/3/",
        ionParts: ["IO", 3],
        charge: -1,
        isPolyatomic: true,
        molarMass: 174.90,
        subscript: 1,
    },
    periodate: {
        ionName: "periodate",
        ionFormula: "IO/4/",
        ionParts: ["IO", 4],
        charge: -1,
        isPolyatomic: true,
        molarMass: 190.90,
        subscript: 1,
    },
    permanganate: {
        ionName: "permanganate",
        ionFormula: "MnO/4/",
        ionParts: ["MnO", 4],
        charge: -1,
        isPolyatomic: true,
        molarMass: 118.94,
        subscript: 1,
    },
    nitrite: {
        ionName: "nitrite",
        ionFormula: "NO/2/",
        ionParts: ["NO", 2],
        charge: -1,
        isPolyatomic: true,
        molarMass: 46.01,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: true,
            Ca: true,
            Ba: true,
            Fe: true,
            Cu: true,
            Ag: false,
            Zn: true,
            Pb: true,
            Al: true,
            Hg: true,
        },
        subscript: 1,
    },
    nitrate: {
        ionName: "nitrate",
        ionFormula: "NO/3/",
        ionParts: ["NO", 3],
        charge: -1,
        isPolyatomic: true,
        molarMass: 46.01,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: true,
            Ca: true,
            Ba: true,
            Fe: true,
            Cu: true,
            Ag: true,
            Zn: true,
            Pb: true,
            Al: true,
            Hg: true,
        },
        subscript: 1,
    },
    hydroxide: {
        ionName: "hydroxide",
        ionFormula: "OH",
        ionParts: ["OH"],
        charge: -1,
        isPolyatomic: true,
        molarMass: 17.01,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: false,
            Ca: false,
            Ba: true,
            Fe: false,
            Cu: false,
            Ag: false,
            Zn: false,
            Pb: false,
            Al: false,
            Hg: false,
        },
        subscript: 1,
    },
    bisulfite: {
        ionName: "bisulfite",
        ionFormula: "HSO/3/",
        ionParts: ["HSO", 3],
        charge: -1,
        isPolyatomic: true,
        molarMass: 81.08,
        subscript: 1,
    },
    bisulfate: {
        ionName: "bisulfate",
        ionFormula: "HSO/4/",
        ionParts: ["HSO", 4],
        charge: -1,
        isPolyatomic: true,
        molarMass: 97.08,
        subscript: 1,
    },
    thiocyanate: {
        ionName: "thiocyanate",
        ionFormula: "SCN",
        ionParts: ["SCN"],
        charge: -1,
        isPolyatomic: true,
        molarMass: 58.09,
        subscript: 1,
    },
    carbonate: {
        ionName: "carbonate",
        ionFormula: "CO/3/",
        ionParts: ["CO", 3],
        charge: -2,
        isPolyatomic: true,
        molarMass: 60.01,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: false,
            Ca: false,
            Ba: false,
            Fe: false,
            Cu: false,
            Ag: false,
            Zn: false,
            Pb: false,
            Al: true,
            Hg: false,
        }, 
        subscript: 1,
    },
    oxalate: {
        ionName: "oxalate",
        ionFormula: "C/2/O/4/",
        ionParts: ["C", 2, "O", 4],
        charge: -2,
        isPolyatomic: true,
        molarMass: 88.02,
        subscript: 1,
    },
    chromate: {
        ionName: "chromate",
        ionFormula: "CrO/4/",
        ionParts: ["CrO", 4],
        charge: -2,
        isPolyatomic: true,
        molarMass: 116.00,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: true,
            Ca: true,
            Ba: false,
            Fe: false,
            Cu: false,
            Ag: false,
            Zn: true,
            Pb: false,
            Al: false,
            Hg: false,
        },
        subscript: 1,
    },
    dichromate: {
        ionName: "dichromate",
        ionFormula: "Cr/2/O/7/",
        ionParts: ["Cr", 2, "O", 7],
        charge: -2,
        isPolyatomic: true,
        molarMass: 216.00,
        subscript: 1,
    },
    selenite: {
        ionName: "selenite",
        ionFormula: "SeO/3/",
        ionParts: ["SeO", 3],
        charge: -2,
        isPolyatomic: true,
        molarMass: 126.97,
        subscript: 1,
    },
    selenate: {
        ionName: "selenate",
        ionFormula: "SeO/4/",
        ionParts: ["SeO", 4],
        charge: -2,
        isPolyatomic: true,
        molarMass: 142.97,
        subscript: 1,
    },
    sulfite: {
        ionName: "sulfite",
        ionFormula: "SO/3/",
        ionParts: ["SO", 3],
        charge: -2,
        isPolyatomic: true,
        molarMass: 80.07,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: true,
            Ca: false,
            Ba: false,
            Fe: true,
            Cu: true,
            Ag: false,
            Zn: false,
            Pb: false,
            Al: true,
            Hg: false,
        },
        subscript: 1,
    },
    sulfate: {
        ionName: "sulfate",
        ionFormula: "SO/4/",
        ionParts: ["SO", 4],
        charge: -2,
        isPolyatomic: true,
        molarMass: 96.07,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: true,
            Na: true,
            K: true,
            Mg: true,
            Ca: false,
            Ba: false,
            Fe: true,
            Cu: true,
            Ag: false,
            Zn: true,
            Pb: false,
            Al: true,
            Hg: false,
        },
        subscript: 1,
    },
    persulfate: {
        ionName: "persulfate",
        ionFormula: "SO/5/",
        ionParts: ["SO", 5],
        charge: -2,
        isPolyatomic: true,
        molarMass: 112.07,
        subscript: 1,
    },
    tellurite: {
        ionName: "tellurite",
        ionFormula: "TeO/3/",
        ionParts: ["TeO", 3],
        charge: -2,
        isPolyatomic: true,
        molarMass: 175.6,
        subscript: 1,
    },
    tellurate: {
        ionName: "tellurate",
        ionFormula: "TeO/4/",
        ionParts: ["TeO", 4],
        charge: -2,
        isPolyatomic: true,
        molarMass: 191.6,
        subscript: 1,
    },
    arsenite: {
        ionName: "arsenite",
        ionFormula: "AsO/3/",
        ionParts: ["AsO", 3],
        charge: -3,
        isPolyatomic: true,
        molarMass: 122.92,
        subscript: 1,
    },
    arsenate: {
        ionName: "arsenate",
        ionFormula: "AsO/4/",
        ionParts: ["AsO", 4],
        charge: -3,
        isPolyatomic: true,
        molarMass: 138.92,
        subscript: 1,
    },
    phosphite: {
        ionName: "phosphite",
        ionFormula: "PO/3/",
        ionParts: ["PO", 3],
        charge: -3,
        isPolyatomic: true,
        molarMass: 78.97,
        subscript: 1,
    },
    phosphate: {
        ionName: "phosphate",
        ionFormula: "PO/4/",
        ionParts: ["PO", 4],
        charge: -3,
        isPolyatomic: true,
        molarMass: 94.97,
        solubilityTable: {
            Rb: true, 
            ammonium: true,
            Li: false,
            Na: true,
            K: true,
            Mg: false,
            Ca: false,
            Ba: false,
            Fe: false,
            Cu: false,
            Ag: false,
            Zn: false,
            Pb: false,
            Al: false,
            Hg: false,
        },
        subscript: 1,
    },
}