import { ActivitySeries } from "./interfaces"

// The greater the priority, the more reactive the metal or nonmetal
export const activitySeriesMetal: ActivitySeries[] = [
    {
        elementSymbol: "Mg",
        elementName: "magnesium",
        possibleCharges: [2],
        priority: 910,
        isTransitionMetal: false,
    },
    {
        elementSymbol: "Al",
        elementName: "aluminum",
        possibleCharges: [3],
        priority: 900,
        isTransitionMetal: false,
    },
    {
        elementSymbol: "Ti",
        elementName: "titanium",
        possibleCharges: [2, 3, 4],
        priority: 890,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Mn",
        elementName: "manganese",
        possibleCharges: [2, 7],
        priority: 880,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Zn",
        elementName: "zinc",
        possibleCharges: [2],
        priority: 870,
        isTransitionMetal: false,
    },
    {
        elementSymbol: "Cr",
        elementName: "chromium",
        possibleCharges: [3, 6],
        priority: 860,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Fe",
        elementName: "iron",
        possibleCharges: [2, 3],
        priority: 850,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Co",
        elementName: "cobalt",
        possibleCharges: [2, 3],
        priority: 840,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Ni",
        elementName: "nickel",
        possibleCharges: [2],
        priority: 830,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Sn",
        elementName: "tin",
        possibleCharges: [2, 4],
        priority: 820,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Pb",
        elementName: "lead",
        possibleCharges: [2, 4],
        priority: 810,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "H",
        elementName: "hydrogen",
        possibleCharges: [1],
        priority: 800,
        isTransitionMetal: false,
    },
    {
        elementSymbol: "Cu",
        elementName: "copper",
        possibleCharges: [1, 2],
        priority: 790,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Ag",
        elementName: "silver",
        possibleCharges: [1],
        priority: 780,
        isTransitionMetal: false,
    },
    {
        elementSymbol: "Hg",
        elementName: "mercury",
        possibleCharges: [1, 2],
        priority: 770,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Pt",
        elementName: "platinum",
        possibleCharges: [2, 4],
        priority: 760,
        isTransitionMetal: true,
    },
    {
        elementSymbol: "Au",
        elementName: "gold",
        possibleCharges: [1, 3],
        priority: 750,
        isTransitionMetal: true,
    },
]

export const activitySeriesNonmetal: ActivitySeries[] = [
    {
        elementSymbol: "F",
        elementName: "fluorine",
        possibleCharges: [-1],
        priority: 4,
        isTransitionMetal: false,
    },
    {
        elementSymbol: "Cl",
        elementName: "chlorine",
        possibleCharges: [-1],
        priority: 3,
        isTransitionMetal: false,
    },
    {
        elementSymbol: "Br",
        elementName: "bromine",
        possibleCharges: [-1],
        priority: 2,
        isTransitionMetal: false,
    },
    {
        elementSymbol: "I",
        elementName: "iodine",
        possibleCharges: [-1],
        priority: 1,
        isTransitionMetal: false,
    },
]