import { Element } from "./interfaces"

export const ionNameToElement: {[member: string]: Element} = {
    lithium: {
        elementName: "lithium",
        elementSymbol: "Li",
        isDiatomic: false,
        state: "s",
    },
    sodium: {
        elementName: "sodium",
        elementSymbol: "Na",
        isDiatomic: false,
        state: "s",
    },
    potassium: {
        elementName: "potassium",
        elementSymbol: "K",
        isDiatomic: false,
        state: "s",
    },
    rubidium: {
        elementName: "rubidium",
        elementSymbol: "Rb",
        isDiatomic: false,
        state: "s",
    },
   cesium: {
        elementName: "cesium",
        elementSymbol: "Cs",
        isDiatomic: false,
        state: "s",
    },
    silver: {
        elementName: "silver",
        elementSymbol: "Ag",
        isDiatomic: false,
        state: "s",
    },
    magnesium: {
        elementName: "magnesium",
        elementSymbol: "Mg",
        isDiatomic: false,
        state: "s",
    },
    calcium: {
        elementName: "calcium",
        elementSymbol: "Ca",
        isDiatomic: false,
        state: "s",
    },
    strontium: {
        elementName: "strontium",
        elementSymbol: "Sr",
        isDiatomic: false,
        state: "s",
    },
    barium: {
        elementName: "barium",
        elementSymbol: "Ba",
        isDiatomic: false,
        state: "s",
    },
    cadmium: {
        elementName: "cadmium",
        elementSymbol: "Cd",
        isDiatomic: false,
        state: "s",
    },
    zinc: {
        elementName: "zinc",
        elementSymbol: "Zn",
        isDiatomic: false,
        state: "s",
    },
    aluminum: {
        elementName: "aluminum",
        elementSymbol: "Al",
        isDiatomic: false,
        state: "s",
    },
    fluoride: {
        elementName: "fluorine",
        elementSymbol: "F",
        isDiatomic: true,
        state: "g",
    },
    chloride: {
        elementName: "chlorine",
        elementSymbol: "Cl",
        isDiatomic: true,
        state: "g",
    },
    bromide: {
        elementName: "bromine",
        elementSymbol: "Br",
        isDiatomic: true,
        state: "l",
    },
    iodide: {
        elementName: "iodine",
        elementSymbol: "I",
        isDiatomic: true,
        state: "s",
    },
    oxide: {
        elementName: "oxygen",
        elementSymbol: "O",
        isDiatomic: true,
        state: "g",
    },
    sulfide: {
        elementName: "sulfur",
        elementSymbol: "S",
        isDiatomic: false,
        state: "s",
    },
    nitride: {
        elementName: "nitrogen",
        elementSymbol: "N",
        isDiatomic: true,
        state: "g",
    },
    phosphide: {
        elementName: "phosphorus",
        elementSymbol: "P",
        isDiatomic: false,
        state: "s",
    },
    carbide: {
        elementName: "carbon",
        elementSymbol: "C",
        isDiatomic: false,
        state: "s",
    },
    "copper(I)": {
        elementName: "copper",
        elementSymbol: "Cu",
        isDiatomic: false,
        state: "s",
    },
    "gold(I)": {
        elementName: "gold",
        elementSymbol: "Au",
        isDiatomic: false,
        state: "s",
    },
    "copper(II)": {
        elementName: "copper",
        elementSymbol: "Cu",
        isDiatomic: false,
        state: "s",
    },
    "cobalt(II)": {
        elementName: "cobalt",
        elementSymbol: "Co",
        isDiatomic: false,
        state: "s",
    },
    "iron(II)": {
        elementName: "iron",
        elementSymbol: "Fe",
        isDiatomic: false,
        state: "s",
    },
    "lead(II)": {
        elementName: "lead",
        elementSymbol: "Pb",
        isDiatomic: false,
        state: "s",
    },
    "mercury(II)":{
        elementName: "mercury",
        elementSymbol: "Hg",
        isDiatomic: false,
        state: "l",
    },
    "nickel(II)": {
        elementName: "nickel",
        elementSymbol: "Ni",
        isDiatomic: false,
        state: "s",
    },
    "platinum(II)": {
        elementName: "platinum",
        elementSymbol: "Pg",
        isDiatomic: false,
        state: "s",
    },
    "tin(II)": {
        elementName: "tin",
        elementSymbol: "Sn",
        isDiatomic: false,
        state: "s",
    },
    "titanium(II)": {
        elementName: "titanium",
        elementSymbol: "Ti",
        isDiatomic: false,
        state: "s",
    },
    "chromium(III)": {
        elementName: "chromium",
        elementSymbol: "Cr",
        isDiatomic: false,
        state: "s",
    },
    "cobalt(III)": {
        elementName: "cobalt",
        elementSymbol: "Co",
        isDiatomic: false,
        state: "s",
    },
    "gold(III)": {
        elementName: "gold",
        elementSymbol: "Au",
        isDiatomic: false,
        state: "s",
    },
    "iron(III)": {
        elementName: "iron",
        elementSymbol: "Fe",
        isDiatomic: false,
        state: "s",
    },
    "manganese(III)": {
        elementName: "manganese",
        elementSymbol: "Mn",
        isDiatomic: false,
        state: "s",
    },
    "nickel(III)": {
        elementName: "nickel",
        elementSymbol: "Ni",
        isDiatomic: false,
        state: "s",
    },
    "scandium(III)": {
        elementName: "scandium",
        elementSymbol: "Sc",
        isDiatomic: false,
        state: "s",
    },
    "vanadium(III)": {
        elementName: "vanadium",
        elementSymbol: "V",
        isDiatomic: false,
        state: "s",
    },
    "lead(IV)": {
        elementName: "lead",
        elementSymbol: "Pb",
        isDiatomic: false,
        state: "s",
    },
    "osmium(IV)": {
        elementName: "osmium",
        elementSymbol: "Os",
        isDiatomic: false,
        state: "s",
    },
    "palladium(IV)": {
        elementName: "palladium",
        elementSymbol: "Pd",
        isDiatomic: false,
        state: "s",
    },
    "platinum(IV)": {
        elementName: "platinum",
        elementSymbol: "Pt",
        isDiatomic: false,
        state: "s",
    },
    "tin(IV)": {
        elementName: "tin",
        elementSymbol: "Sn",
        isDiatomic: false,
        state: "s",
    },
    "titanium(IV)": {
        elementName: "titanium",
        elementSymbol: "Ti",
        isDiatomic: false,
        state: "s",
    },
    "chromium(V)": {
        elementName: "chromium",
        elementSymbol: "Cr",
        isDiatomic: false,
        state: "s",
    },
    "manganese(V)": {
        elementName: "manganese",
        elementSymbol: "Mn",
        isDiatomic: false,
        state: "s",
    },
    "vanadium(V)": {
        elementName: "vanadium",
        elementSymbol: "V",
        isDiatomic: false,
        state: "s",
    },
    "tungsten(V)": {
        elementName: "tungsten",
        elementSymbol: "W",
        isDiatomic: false,
        state: "s",
    },
    "chromium(VI)": {
        elementName: "chromium",
        elementSymbol: "Cr",
        isDiatomic: false,
        state: "s",
    },
    "molybdenum(VI)": {
        elementName: "molybdenum",
        elementSymbol: "Mo",
        isDiatomic: false,
        state: "s",
    },
    "osmium(VI)": {
        elementName: "osmium",
        elementSymbol: "Os",
        isDiatomic: false,
        state: "s",
    },
    "ruthenium(VI)": {
        elementName: "ruthenium",
        elementSymbol: "Ru",
        isDiatomic: false,
        state: "s",
    },
    "manganese(VII)": {
        elementName: "manganese",
        elementSymbol: "Mn",
        isDiatomic: false,
        state: "s",
    },
    "rhenium(VII)": {
        elementName: "rhenium",
        elementSymbol: "Re",
        isDiatomic: false,
        state: "s",
    },
    "osmium(VIII)": {
        elementName: "osmium",
        elementSymbol: "Os",
        isDiatomic: false,
        state: "s",
    },
    "ruthenium(VIII)": {
        elementName: "ruthenium",
        elementSymbol: "Ru",
        isDiatomic: false,
        state: "s",
    },
}