import { SolubilityCations, DRIons } from "./interfaces"

export const solubilityCationNames: string[] = [
    "ammonium", "lithium", "sodium", "potassium", "magnesium", "calcium", "barium", "iron", "copper", "silver", "zinc", "lead", "aluminum", "mercury",
];

export const solubilityAnionNames: string[] = [
    "fluoride", "chloride", "bromide", "iodide", "chlorate", "hydroxide", "sulfite", "sulfate", "carbonate", "nitrite", "nitrate", "phosphate", "acetate", "chromate",
]

export const solubilityTable: SolubilityCations = {
    ammonium: {
        fluoride: true,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: true,
        sulfite: true,
        sulfate: true,
        carbonate: true,
        nitrite: true,
        nitrate: true,
        phosphate: true,
        acetate: true,
        chromate: true,
    },
    lithium: {
        fluoride: false,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: true,
        sulfite: true,
        sulfate: true,
        carbonate: true,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: true,
        chromate: true,
    },
    sodium: {
        fluoride: true,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: true,
        sulfite: true,
        sulfate: true,
        carbonate: true,
        nitrite: true,
        nitrate: true,
        phosphate: true,
        acetate: true,
        chromate: true,
    },
    potassium: {
        fluoride: true,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: true,
        sulfite: true,
        sulfate: true,
        carbonate: true,
        nitrite: true,
        nitrate: true,
        phosphate: true,
        acetate: true,
        chromate: true,
    },
    magnesium: {
        fluoride: false,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: false,
        sulfite: true,
        sulfate: true,
        carbonate: false,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: true,
        chromate: true,
    },
    calcium: {
        fluoride: false,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: false,
        sulfite: false,
        sulfate: false,
        carbonate: false,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: true,
        chromate: true,
    },
    barium: {
        fluoride: false,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: true,
        sulfite: false,
        sulfate: false,
        carbonate: false,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: true,
        chromate: false,
    },
    iron: {
        fluoride: false,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: false,
        sulfite: true,
        sulfate: true,
        carbonate: false,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: true,
        chromate: false,
    },
    copper: {
        fluoride: true,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: false,
        sulfite: true,
        sulfate: true,
        carbonate: false,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: true,
        chromate: false,
    },
    silver: {
        fluoride: true,
        chloride: false,
        bromide: false,
        iodide: false,
        chlorate: true,
        hydroxide: false,
        sulfite: false,
        sulfate: false,
        carbonate: false,
        nitrite: false,
        nitrate: true,
        phosphate: false,
        acetate: false,
        chromate: false,
    },
    zinc: {
        fluoride: true,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: false,
        sulfite: false,
        sulfate: true,
        carbonate: false,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: true,
        chromate: true,
    },
    lead: {
        fluoride: false,
        chloride: false,
        bromide: false,
        iodide: false,
        chlorate: true,
        hydroxide: false,
        sulfite: false,
        sulfate: false,
        carbonate: false,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: true,
        chromate: false,
    },
    aluminum: {
        fluoride: false,
        chloride: true,
        bromide: true,
        iodide: true,
        chlorate: true,
        hydroxide: false,
        sulfite: true,
        sulfate: true,
        carbonate: true,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: false,
        chromate: false,
    },
    mercury: {
        fluoride: false,
        chloride: false,
        bromide: false,
        iodide: false,
        chlorate: false,
        hydroxide: false,
        sulfite: false,
        sulfate: false,
        carbonate: false,
        nitrite: true,
        nitrate: true,
        phosphate: false,
        acetate: false,
        chromate: false,
    },
}

export const drCations: DRIons = {
    ammonium: {
        ionName: "ammonium",
        ionSymbol: ["NH", 4],
        charge: 1,
        isPolyatomic: true,
    },
    lithium: {
        ionName: "lithium",
        ionSymbol: ["Li"],
        charge: 1,
        isPolyatomic: false,
    },
    sodium: {
        ionName: "sodium",
        ionSymbol: ["Na"],
        charge: 1,
        isPolyatomic: false,
    },
    potassium: {
        ionName: "potassium",
        ionSymbol: ["K"],
        charge: 1,
        isPolyatomic: false,
    },
    magnesium: {
        ionName: "magnesium",
        ionSymbol: ["Mg"],
        charge: 2,
        isPolyatomic: false,
    },
    calcium: {
        ionName: "calcium",
        ionSymbol: ["Ca"],
        charge: 2,
        isPolyatomic: false,
    },
    barium: {
        ionName: "barium",
        ionSymbol: ["Ba"],
        charge: 2,
        isPolyatomic: false,
    },
    iron: {
        ionName: "iron(III)",
        ionSymbol: ["Fe"],
        charge: 3,
        isPolyatomic: false,
    },
    copper: {
        ionName: "copper(II)",
        ionSymbol: ["Cu"],
        charge: 2,
        isPolyatomic: false,
    },
    silver: {
        ionName: "silver",
        ionSymbol: ["Ag"],
        charge: 1,
        isPolyatomic: false,
    },
    zinc: {
        ionName: "zinc",
        ionSymbol: ["Zn"],
        charge: 2,
        isPolyatomic: false,
    },
    lead: {
        ionName: "lead(II)",
        ionSymbol: ["Pb"],
        charge: 2,
        isPolyatomic: false,
    },
    aluminum: {
        ionName: "aluminum",
        ionSymbol: ["Al"],
        charge: 3,
        isPolyatomic: false,
    },
    mercury: {
        ionName: "mercury(II)",
        ionSymbol: ["Hg"],
        charge: 2,
        isPolyatomic: false,
    }
}

export const drAnions: DRIons = {
    fluoride: {
        ionName: "fluoride",
        ionSymbol: ["F"],
        charge: -1,
        isPolyatomic: false,
    },
    chloride: {
        ionName: "chloride",
        ionSymbol: ["Cl"],
        charge: -1,
        isPolyatomic: false,
    },
    bromide: {
        ionName: "bromide",
        ionSymbol: ["Br"],
        charge: -1,
        isPolyatomic: false,
    },
    iodide: {
        ionName: "iodide",
        ionSymbol: ["I"],
        charge: -1,
        isPolyatomic: false,
    },
    chlorate: {
        ionName: "chlorate",
        ionSymbol: ["ClO", 3],
        charge: -1,
        isPolyatomic: true,
    },
    hydroxide: {
        ionName: "hydroxide",
        ionSymbol: ["OH"],
        charge: -1,
        isPolyatomic: true,
    },
    sulfite: {
        ionName: "sulfite",
        ionSymbol: ["SO", 3],
        charge: -2,
        isPolyatomic: true,
    },
    sulfate: {
        ionName: "sulfate",
        ionSymbol: ["SO", 4],
        charge: -2,
        isPolyatomic: true,
    },
    carbonate: {
        ionName: "carbonate",
        ionSymbol: ["CO", 3],
        charge: -2,
        isPolyatomic: true,
    },
    nitrite: {
        ionName: "nitrite",
        ionSymbol: ["NO", 2],
        charge: -1,
        isPolyatomic: true,
    },
    nitrate: {
        ionName: "nitrate",
        ionSymbol: ["NO", 3],
        charge: -1,
        isPolyatomic: true,
    },
    phosphate: {
        ionName: "phosphate",
        ionSymbol: ["PO", 4],
        charge: -3,
        isPolyatomic: true,
    },
    acetate: {
        ionName: "acetate",
        ionSymbol: ["CH", 3, "COO"],
        charge: -1,
        isPolyatomic: true,
    },
    chromate: {
        ionName: "chromate",
        ionSymbol: ["CrO", 4],
        charge: -2,
        isPolyatomic: true,
    },
}