import { ElementData, BooleanDict } from "./interfaces";

export const elementData: ElementData = {
    H: {
        elementSymbol: "H",
        elementName: "hydrogen",
        group: 1,
        period: 1,
        isDiatomic: true,
        ionName: "hydride",
        possibleCharges: [-1, 1],
        electronegativity: 2.1,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 800,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "g",
        molarMass: 1.01,
        quantity: 1,
    },
    Li: {
        elementSymbol: "Li",
        elementName: "lithium",
        group: 1,
        period: 2,
        isDiatomic: false,
        ionName: "lithium",
        possibleCharges: [1],
        electronegativity: 1.0,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: false,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: true,
            sulfite: true,
            sulfate: true,
            carbonate: true,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: true,
            chromate: true,
        },
        stateOfMatter: "s",
        molarMass: 6.94,
        quantity: 1,
    },
    C: {
        elementSymbol: "C",
        elementName: "carbon",
        group: 14,
        period: 2,
        isDiatomic: false,
        ionName: "carbide",
        possibleCharges: [-4, 4],
        electronegativity: 2.5,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 12.01,
        quantity: 1,
    },
    N: {
        elementSymbol: "N",
        elementName: "nitrogen",
        group: 15,
        period: 2,
        isDiatomic: true,
        ionName: "nitride",
        possibleCharges: [-3, 5],
        electronegativity: 3.0,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "g",
        molarMass: 14.01,
        quantity: 1,
    },
    O: {
        elementSymbol: "O",
        elementName: "oxygen",
        group: 16,
        period: 2,
        isDiatomic: true,
        ionName: "oxide",
        possibleCharges: [-2],
        electronegativity: 3.5,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "g",
        molarMass: 16.00,
        quantity: 1,
    },
    F: {
        elementSymbol: "F",
        elementName: "fluorine",
        group: 17,
        period: 2,
        isDiatomic: true,
        ionName: "fluoride",
        possibleCharges: [-1],
        electronegativity: 4.0,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 4,
        isOnSolubilityTable: true,
        solubilityTable: {
            rubidium: true, 
            ammonium: true,
            lithium: false,
            sodium: true,
            potassium: true,
            magnesium: false,
            calcium: false,
            barium: false,
            iron: false,
            copper: true,
            silver: true,
            zinc: true,
            lead: false,
            aluminum: false,
            mercury: false,
        },
        stateOfMatter: "g",
        molarMass: 19.00,
        quantity: 1,
    },
    Na: {
        elementSymbol: "Na",
        elementName: "sodium",
        group: 1,
        period: 3,
        isDiatomic: false,
        ionName: "sodium",
        possibleCharges: [1],
        electronegativity: 0.9,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: true,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: true,
            sulfite: true,
            sulfate: true,
            carbonate: true,
            nitrite: true,
            nitrate: true,
            phosphate: true,
            acetate: true,
            chromate: true,
        },
        stateOfMatter: "s",
        molarMass: 22.99,
        quantity: 1,
    },
    Mg: {
        elementSymbol: "Mg",
        elementName: "magnesium",
        group: 2,
        period: 3,
        isDiatomic: false,
        ionName: "magnesium",
        possibleCharges: [2],
        electronegativity: 1.2,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 910,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: false,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: false,
            sulfite: true,
            sulfate: true,
            carbonate: false,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: true,
            chromate: true,
        },
        stateOfMatter: "s",
        molarMass: 24.31,
        quantity: 1,
    },
    Al: {
        elementSymbol: "Al",
        elementName: "aluminum",
        group: 13,
        period: 3,
        isDiatomic: false,
        ionName: "aluminum",
        possibleCharges: [3],
        electronegativity: 1.5,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 900,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: false,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: false,
            sulfite: true,
            sulfate: true,
            carbonate: true,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: false,
            chromate: false,
        },
        stateOfMatter: "s",
        molarMass: 26.98,
        quantity: 1,
    },
    Si: {
        elementSymbol: "Si",
        elementName: "silicon",
        group: 14,
        period: 3,
        isDiatomic: false,
        ionName: "silicon",
        possibleCharges: [-4, 4],
        electronegativity: 1.8,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 28.09,
        quantity: 1,
    },
    P: {
        elementSymbol: "P",
        elementName: "phosphorus",
        group: 15,
        period: 3,
        isDiatomic: false,
        ionName: "phosphide",
        possibleCharges: [-3, 3, 5],
        electronegativity: 2.1,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 30.97,
        quantity: 1,
    },
    S: {
        elementSymbol: "S",
        elementName: "sulfur",
        group: 16,
        period: 3,
        isDiatomic: false,
        ionName: "sulfide",
        possibleCharges: [-2, 6],
        electronegativity: 2.5,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 32.07,
        quantity: 1,
    },
    Cl: {
        elementSymbol: "Cl",
        elementName: "chlorine",
        group: 17,
        period: 3,
        isDiatomic: true,
        ionName: "chloride",
        possibleCharges: [-1],
        electronegativity: 3.0,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 3,
        isOnSolubilityTable: true,
        solubilityTable: {
            rubidium: true,
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: true,
            barium: true,
            iron: true,
            copper: true,
            silver: false,
            zinc: true,
            lead: false,
            aluminum: true,
            mercury: false,
        },
        stateOfMatter: "g",
        molarMass: 35.45,
        quantity: 1,
    },
    K: {
        elementSymbol: "K",
        elementName: "potassium",
        group: 1,
        period: 4,
        isDiatomic: false,
        ionName: "potassium",
        possibleCharges: [1],
        electronegativity: 0.8,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: true,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: true,
            sulfite: true,
            sulfate: true,
            carbonate: true,
            nitrite: true,
            nitrate: true,
            phosphate: true,
            acetate: true,
            chromate: true,
        },
        stateOfMatter: "s",
        molarMass: 39.10,
        quantity: 1,
    },
    Ca: {
        elementSymbol: "Ca",
        elementName: "calcium",
        group: 2,
        period: 4,
        isDiatomic: false,
        ionName: "calcium",
        possibleCharges: [2],
        electronegativity: 1.0,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: false,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: false,
            sulfite: false,
            sulfate: false,
            carbonate: false,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: true,
            chromate: true,
        },
        stateOfMatter: "s",
        molarMass: 40.08,
        quantity: 1,
    },
    Sc: {
        elementSymbol: "Sc",
        elementName: "scandium",
        group: 3,
        period: 4,
        isDiatomic: false,
        ionName: "scandium",
        possibleCharges: [3],
        electronegativity: 1.3,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 44.96,
        quantity: 1,
    },
    Ti: {
        elementSymbol: "Ti",
        elementName: "titanium",
        group: 4,
        period: 4,
        isDiatomic: false,
        ionName: "titanium",
        possibleCharges: [2, 4],
        electronegativity: 1.5,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 890,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 47.88,
        quantity: 1,
    },
    V: {
        elementSymbol: "V",
        elementName: "vanadium",
        group: 5,
        period: 4,
        isDiatomic: false,
        ionName: "vanadium",
        possibleCharges: [3, 5],
        electronegativity: 1.6,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 50.94,
        quantity: 1,
    },
    Cr: {
        elementSymbol: "Cr",
        elementName: "chromium",
        group: 6,
        period: 4,
        isDiatomic: false,
        ionName: "chromium",
        possibleCharges: [3, 5, 6],
        electronegativity: 1.6,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 860,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 52.00,
        quantity: 1,
    },
    Mn: {
        elementSymbol: "Mn",
        elementName: "manganese",
        group: 7,
        period: 4,
        isDiatomic: false,
        ionName: "manganese",
        possibleCharges: [3, 5, 7],
        electronegativity: 1.5,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 880,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 54.94,
        quantity: 1,
    },
    Fe: {
        elementSymbol: "Fe",
        elementName: "iron",
        group: 8,
        period: 4,
        isDiatomic: false,
        ionName: "iron",
        possibleCharges: [2, 3],
        electronegativity: 1.8,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 850,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: false,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: false,
            sulfite: true,
            sulfate: true,
            carbonate: false,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: true,
            chromate: false,
        },
        stateOfMatter: "s",
        molarMass: 55.85,
        quantity: 1,
    },
    Co: {
        elementSymbol: "Co",
        elementName: "cobalt",
        group: 9,
        period: 4,
        isDiatomic: false,
        ionName: "cobalt",
        possibleCharges: [2, 3],
        electronegativity: 1.9,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 840,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 58.93,
        quantity: 1,
    },
    Ni: {
        elementSymbol: "Ni",
        elementName: "nickel",
        group: 10,
        period: 4,
        isDiatomic: false,
        ionName: "nickel",
        possibleCharges: [2],
        electronegativity: 1.8,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 830,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 58.69,
        quantity: 1,
    },
    Cu: {
        elementSymbol: "Cu",
        elementName: "copper",
        group: 11,
        period: 4,
        isDiatomic: false,
        ionName: "copper",
        possibleCharges: [1, 2],
        electronegativity: 1.9,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 790,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: true,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: false,
            sulfite: true,
            sulfate: true,
            carbonate: false,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: true,
            chromate: false,
        },
        stateOfMatter: "s",
        molarMass: 63.55,
        quantity: 1,
    },
    Zn: {
        elementSymbol: "Zn",
        elementName: "zinc",
        group: 12,
        period: 4,
        isDiatomic: false,
        ionName: "zinc",
        possibleCharges: [2],
        electronegativity: 1.6,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 870,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: true,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: false,
            sulfite: false,
            sulfate: true,
            carbonate: false,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: true,
            chromate: true,
        },
        stateOfMatter: "s",
        molarMass: 65.38,
        quantity: 1,
    },
    Ge: {
        elementSymbol: "Ge",
        elementName: "germanium",
        group: 14,
        period: 4,
        isDiatomic: false,
        ionName: "germanium",
        possibleCharges: [4],
        electronegativity: 1.8,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 72.63,
        quantity: 1,
    },
    As: {
        elementSymbol: "As",
        elementName: "arsenic",
        group: 15,
        period: 4,
        isDiatomic: false,
        ionName: "arsenide",
        possibleCharges: [3, 5],
        electronegativity: 2.0,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 74.92,
        quantity: 1,
    },
    Se: {
        elementSymbol: "Se",
        elementName: "selenium",
        group: 16,
        period: 4,
        isDiatomic: false,
        ionName: "selenide",
        possibleCharges: [-2, 4],
        electronegativity: 2.4,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 78.97,
        quantity: 1,
    },
    Br: {
        elementSymbol: "Br",
        elementName: "bromine",
        group: 17,
        period: 4,
        isDiatomic: true,
        ionName: "bromide",
        possibleCharges: [-1, 5],
        electronegativity: 2.8,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 2,
        isOnSolubilityTable: true,
        solubilityTable: {
            rubidium: true,
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: true,
            barium: true,
            iron: true,
            copper: true,
            silver: false,
            zinc: true,
            lead: false,
            aluminum: true,
            mercury: false,
        },
        stateOfMatter: "l",
        molarMass: 79.90,
        quantity: 1,
    },
    Kr: {
        elementSymbol: "Kr",
        elementName: "krypton",
        group: 18,
        period: 4,
        isDiatomic: false,
        ionName: "krypton",
        possibleCharges: [0, 2],
        electronegativity: 0,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "g",
        molarMass: 83.80,
        quantity: 1,
    },
    Rb: {
        elementSymbol: "Rb",
        elementName: "rubidium",
        group: 1,
        period: 5,
        isDiatomic: false,
        ionName: "rubidium",
        possibleCharges: [1],
        electronegativity: 0.8,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: true,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: true,
            sulfite: true,
            sulfate: true,
            carbonate: true,
            nitrite: true,
            nitrate: true,
            phosphate: true,
            acetate: true,
            chromate: true,
        },
        stateOfMatter: "s",
        molarMass: 85.47,
        quantity: 1,
    },
    Sr: {
        elementSymbol: "Sr",
        elementName: "strontium",
        group: 2,
        period: 5,
        isDiatomic: false,
        ionName: "strontium",
        possibleCharges: [2],
        electronegativity: 1.0,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 87.62,
        quantity: 1,
    },
    Mo: {
        elementSymbol: "Mo",
        elementName: "molybdenum",
        group: 6,
        period: 5,
        isDiatomic: false,
        ionName: "molybdenum",
        possibleCharges: [4, 6],
        electronegativity: 1.8,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 95.95,
        quantity: 1,
    },
    Ru: {
        elementSymbol: "Ru",
        elementName: "ruthenium",
        group: 8,
        period: 5,
        isDiatomic: false,
        ionName: "ruthenium",
        possibleCharges: [3, 4, 6, 8],
        electronegativity: 2.2,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 101.07,
        quantity: 1,
    },
    Pd: {
        elementSymbol: "Pd",
        elementName: "palladium",
        group: 10,
        period: 5,
        isDiatomic: false,
        ionName: "palladium",
        possibleCharges: [2, 4],
        electronegativity: 2.2,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 106.42,
        quantity: 1,
    },
    Ag: {
        elementSymbol: "Ag",
        elementName: "silver",
        group: 11,
        period: 5,
        isDiatomic: false,
        ionName: "silver",
        possibleCharges: [1],
        electronegativity: 1.9,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 780,
        isOnSolubilityTable: false,
        solubilityTable: {
            fluoride: true,
            chloride: false,
            bromide: false,
            iodide: false,
            chlorate: true,
            hydroxide: false,
            sulfite: false,
            sulfate: false,
            carbonate: false,
            nitrite: false,
            nitrate: true,
            phosphate: false,
            acetate: false,
            chromate: false,
        },
        stateOfMatter: "s",
        molarMass: 107.87,
        quantity: 1,
    },
    Cd: {
        elementSymbol: "Cd",
        elementName: "cadmium",
        group: 12,
        period: 5,
        isDiatomic: false,
        ionName: "cadmium",
        possibleCharges: [2],
        electronegativity: 1.7,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 112.41,
        quantity: 1,
    },
    Sn: {
        elementSymbol: "Sn",
        elementName: "cadmium",
        group: 14,
        period: 5,
        isDiatomic: false,
        ionName: "tin",
        possibleCharges: [2, 4],
        electronegativity: 1.8,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 820,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 118.71,
        quantity: 1,
    },
    Te: {
        elementSymbol: "Te",
        elementName: "tellurium",
        group: 16,
        period: 5,
        isDiatomic: false,
        ionName: "telluride",
        possibleCharges: [4],
        electronegativity: 2.1,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 127.6,
        quantity: 1,
    },
    I: {
        elementSymbol: "I",
        elementName: "iodine",
        group: 17,
        period: 5,
        isDiatomic: true,
        ionName: "iodide",
        possibleCharges: [-1, 5],
        electronegativity: 2.5,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: true,
        activitySeriesPriority: 1,
        isOnSolubilityTable: true,
        solubilityTable: {
            rubidium: true,
            ammonium: true,
            lithium: true,
            sodium: true,
            potassium: true,
            magnesium: true,
            calcium: true,
            barium: true,
            iron: true,
            copper: true,
            silver: false,
            zinc: true,
            lead: false,
            aluminum: true,
            mercury: false,
        },
        stateOfMatter: "s",
        molarMass: 126.90,
        quantity: 1,
    },
    Xe: {
        elementSymbol: "Xe",
        elementName: "xenon",
        group: 18,
        period: 5,
        isDiatomic: false,
        ionName: "xenon",
        possibleCharges: [0, 2, 4, 6],
        electronegativity: 0,
        isMetal: false,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "g",
        molarMass: 131.29,
        quantity: 1,
    },
    Cs: {
        elementSymbol: "Cs",
        elementName: "cesium",
        group: 1,
        period: 6,
        isDiatomic: false,
        ionName: "cesium",
        possibleCharges: [1],
        electronegativity: 0.7,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: true,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: true,
            sulfite: true,
            sulfate: true,
            carbonate: true,
            nitrite: true,
            nitrate: true,
            phosphate: true,
            acetate: true,
            chromate: true,
        },
        stateOfMatter: "s",
        molarMass: 132.91,
        quantity: 1,
    },
    Ba: {
        elementSymbol: "Ba",
        elementName: "barium",
        group: 2,
        period: 6,
        isDiatomic: false,
        ionName: "barium",
        possibleCharges: [2],
        electronegativity: 0.9,
        isMetal: true,
        needsRomanNumerals: false,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: false,
            chloride: true,
            bromide: true,
            iodide: true,
            chlorate: true,
            hydroxide: true,
            sulfite: false,
            sulfate: false,
            carbonate: false,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: true,
            chromate: false,
        },
        stateOfMatter: "s",
        molarMass: 137.33,
        quantity: 1,
    },
    W: {
        elementSymbol: "W",
        elementName: "tungsten",
        group: 6,
        period: 6,
        isDiatomic: false,
        ionName: "tungsten",
        possibleCharges: [4, 5, 6],
        electronegativity: 1.7,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 183.85,
        quantity: 1,
    },
    Re: {
        elementSymbol: "Re",
        elementName: "rhenium",
        group: 7,
        period: 6,
        isDiatomic: false,
        ionName: "rhenium",
        possibleCharges: [3, 4, 5, 7],
        electronegativity: 1.9,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 186.21,
        quantity: 1,
    },
    Os: {
        elementSymbol: "Os",
        elementName: "osmium",
        group: 8,
        period: 6,
        isDiatomic: false,
        ionName: "osmium",
        possibleCharges: [4, 6, 8],
        electronegativity: 2.2,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: false,
        activitySeriesPriority: Infinity,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 190.23,
        quantity: 1,
    },
    Pt: {
        elementSymbol: "Pt",
        elementName: "platinum",
        group: 10,
        period: 6,
        isDiatomic: false,
        ionName: "platinum",
        possibleCharges: [2, 4],
        electronegativity: 2.2,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 760,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 195.08,
        quantity: 1,
    },
    Au: {
        elementSymbol: "Au",
        elementName: "gold",
        group: 11,
        period: 6,
        isDiatomic: false,
        ionName: "gold",
        possibleCharges: [1, 3],
        electronegativity: 2.4,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 0,
        isOnSolubilityTable: false,
        solubilityTable: {} as BooleanDict,
        stateOfMatter: "s",
        molarMass: 196.97,
        quantity: 1,
    },
    Hg: {
        elementSymbol: "Hg",
        elementName: "mercury",
        group: 12,
        period: 6,
        isDiatomic: false,
        ionName: "mercury",
        possibleCharges: [2],
        electronegativity: 2.4,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 770,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: false,
            chloride: false,
            bromide: false,
            iodide: false,
            chlorate: false,
            hydroxide: false,
            sulfite: false,
            sulfate: false,
            carbonate: false,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: false,
            chromate: false,
        },
        stateOfMatter: "l",
        molarMass: 200.59,
        quantity: 1,
    },
    Pb: {
        elementSymbol: "Pb",
        elementName: "lead",
        group: 14,
        period: 6,
        isDiatomic: false,
        ionName: "lead",
        possibleCharges: [2, 4],
        electronegativity: 1.9,
        isMetal: true,
        needsRomanNumerals: true,
        isOnActivitySeries: true,
        activitySeriesPriority: 810,
        isOnSolubilityTable: true,
        solubilityTable: {
            fluoride: false,
            chloride: false,
            bromide: false,
            iodide: false,
            chlorate: true,
            hydroxide: false,
            sulfite: false,
            sulfate: false,
            carbonate: false,
            nitrite: true,
            nitrate: true,
            phosphate: false,
            acetate: true,
            chromate: false,
        },
        stateOfMatter: "s",
        molarMass: 207.2,
        quantity: 1,
    },
}