import { Ion } from "../../interfaces"

export const acidAnions: Ion[] = [
    {
        ionName: "fluoride",
        ionSymbol: ["F"],
        charge: -1,
        isPolyatomic: false,
    },
    {
        ionName: "chloride",
        ionSymbol: ["Cl"],
        charge: -1,
        isPolyatomic: false,
    },
    {
        ionName: "bromide",
        ionSymbol: ["Br"],
        charge: -1,
        isPolyatomic: false,
    },
    {
        ionName: "iodide",
        ionSymbol: ["I"],
        charge: -1,
        isPolyatomic: false,
    },
    {
        ionName: "acetate",
        ionSymbol: ["CH", 3, "COO"],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "cyanide",
        ionSymbol: ["CN"],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "hypobromite",
        ionSymbol: ["BrO"],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "bromite",
        ionSymbol: ["BrO", 2],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "bromate",
        ionSymbol: ["BrO", 3],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "perbromate",
        ionSymbol: ["BrO", 4],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "hypochlorite",
        ionSymbol: ["ClO"],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "chlorite",
        ionSymbol: ["ClO", 2],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "chlorate",
        ionSymbol: ["ClO", 3],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "perchlorate",
        ionSymbol: ["ClO", 4],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "hypoiodite",
        ionSymbol: ["IO"],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "iodite",
        ionSymbol: ["IO", 2],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "iodate",
        ionSymbol: ["IO", 3],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "periodate",
        ionSymbol: ["IO", 4],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "permanganate",
        ionSymbol: ["MnO", 4],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "nitrite",
        ionSymbol: ["NO", 2],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "nitrate",
        ionSymbol: ["NO", 3],
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "carbonate",
        ionSymbol: ["CO", 3],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "oxalate",
        ionSymbol: ["C", 2, "O", 4],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "chromate",
        ionSymbol: ["CrO", 4],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "dichromate",
        ionSymbol: ["Cr", 2, "O", 7],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "selenite",
        ionSymbol: ["SeO", 3],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "selenate",
        ionSymbol: ["SeO", 4],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "sulfite",
        ionSymbol: ["SO", 3],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "sulfate",
        ionSymbol: ["SO", 4],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "persulfate",
        ionSymbol: ["SO", 5],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "tellurite",
        ionSymbol: ["TeO", 3],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "tellurate",
        ionSymbol: ["TeO", 4],
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "arsenite",
        ionSymbol: ["AsO", 3],
        charge: -3,
        isPolyatomic: true,
    },
    {
        ionName: "arsenate",
        ionSymbol: ["AsO", 4],
        charge: -3,
        isPolyatomic: true,
    },
    {
        ionName: "phosphite",
        ionSymbol: ["PO", 3],
        charge: -3,
        isPolyatomic: true,
    },
    {
        ionName: "phosphate",
        ionSymbol: ["PO", 4],
        charge: -3,
        isPolyatomic: true,
    },
]