import { Ion } from "../../interfaces"

export const acidAnions: Ion[] = [
    {
        ionName: "fluoride",
        ionSymbol: "F",
        charge: -1,
        isPolyatomic: false,
    },
    {
        ionName: "chloride",
        ionSymbol: "Cl",
        charge: -1,
        isPolyatomic: false,
    },
    {
        ionName: "bromide",
        ionSymbol: "Br",
        charge: -1,
        isPolyatomic: false,
    },
    {
        ionName: "iodide",
        ionSymbol: "I",
        charge: -1,
        isPolyatomic: false,
    },
    {
        ionName: "acetate",
        ionSymbol: "CH3COO",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "cyanide",
        ionSymbol: "CN",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "hypobromite",
        ionSymbol: "BrO",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "bromite",
        ionSymbol: "BrO2",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "bromate",
        ionSymbol: "BrO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "perbromate",
        ionSymbol: "BrO4",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "hypochlorite",
        ionSymbol: "ClO",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "chlorite",
        ionSymbol: "ClO2",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "chlorate",
        ionSymbol: "ClO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "perchlorate",
        ionSymbol: "ClO4",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "hypoiodite",
        ionSymbol: "IO",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "iodite",
        ionSymbol: "IO2",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "iodate",
        ionSymbol: "IO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "periodate",
        ionSymbol: "IO4",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "nitrite",
        ionSymbol: "NO2",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "nitrate",
        ionSymbol: "NO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        ionName: "carbonate",
        ionSymbol: "CO3",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "oxalate",
        ionSymbol: "C2O4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "chromate",
        ionSymbol: "CrO4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "dichromate",
        ionSymbol: "Cr2O7",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "selenite",
        ionSymbol: "SeO3",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "selenate",
        ionSymbol: "SeO4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "sulfite",
        ionSymbol: "SO3",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "sulfate",
        ionSymbol: "SO4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "persulfate",
        ionSymbol: "SO5",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "tellurite",
        ionSymbol: "TeO3",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "tellurate",
        ionSymbol: "TeO4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        ionName: "arsenite",
        ionSymbol: "AsO3",
        charge: -3,
        isPolyatomic: true,
    },
    {
        ionName: "arsenate",
        ionSymbol: "AsO4",
        charge: -3,
        isPolyatomic: true,
    },
    {
        ionName: "phosphite",
        ionSymbol: "PO3",
        charge: -3,
        isPolyatomic: true,
    },
    {
        ionName: "phosphate",
        ionSymbol: "PO4",
        charge: -3,
        isPolyatomic: true,
    },
]