import { Ion } from "../../interfaces"

export const polyatomicAnions: Ion[] = [
    {
        name: "acetate",
        symbol: "CH3COO",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "cyanide",
        symbol: "CN",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "bicarbonate",
        symbol: "HCO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "hypobromite",
        symbol: "BrO",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "bromite",
        symbol: "BrO2",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "bromate",
        symbol: "BrO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "perbromate",
        symbol: "BrO4",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "hypochlorite",
        symbol: "ClO",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "chlorite",
        symbol: "ClO2",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "chlorate",
        symbol: "ClO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "perchlorate",
        symbol: "ClO4",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "hypoiodite",
        symbol: "IO",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "iodite",
        symbol: "IO2",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "iodate",
        symbol: "IO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "periodate",
        symbol: "IO4",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "permanganate",
        symbol: "MnO4",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "nitrite",
        symbol: "NO2",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "nitrate",
        symbol: "NO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "hydroxide",
        symbol: "OH",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "bisulfite",
        symbol: "HSO3",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "bisulfate",
        symbol: "HSO4",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "thiocyanate",
        symbol: "SCN",
        charge: -1,
        isPolyatomic: true,
    },
    {
        name: "carbonate",
        symbol: "CO3",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "oxalate",
        symbol: "C2O4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "chromate",
        symbol: "CrO4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "dichromate",
        symbol: "Cr2O7",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "selenite",
        symbol: "SeO3",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "selenate",
        symbol: "SeO4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "sulfite",
        symbol: "SO3",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "sulfate",
        symbol: "SO4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "persulfate",
        symbol: "SO5",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "tellurite",
        symbol: "TeO3",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "tellurate",
        symbol: "TeO4",
        charge: -2,
        isPolyatomic: true,
    },
    {
        name: "arsenite",
        symbol: "AsO3",
        charge: -3,
        isPolyatomic: true,
    },
    {
        name: "arsenate",
        symbol: "AsO4",
        charge: -3,
        isPolyatomic: true,
    },
    {
        name: "phosphite",
        symbol: "PO3",
        charge: -3,
        isPolyatomic: true,
    },
    {
        name: "phosphate",
        symbol: "PO4",
        charge: -3,
        isPolyatomic: true,
    },
]