import { Ion } from "../../interfaces"

export const transitionMetalCations: Ion[] = [
    {
        name: "copper(I)",
        symbol: "Cu",
        charge: 1,
        isPolyatomic: false,
    },
    {
        name: "gold(I)",
        symbol: "Au",
        charge: 1,
        isPolyatomic: false,
    },
    {
        name: "copper(II)",
        symbol: "Cu",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "cobalt(II)",
        symbol: "Co",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "iron(II)",
        symbol: "Fe",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "lead(II)",
        symbol: "Pb",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "mercury(II)",
        symbol: "Hg",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "nickel(II)",
        symbol: "Ni",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "platinum(II)",
        symbol: "Pt",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "tin(II)",
        symbol: "Sn",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "titanium(II)",
        symbol: "Ti",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "chromium(III)",
        symbol: "Cr",
        charge: 2,
        isPolyatomic: false,
    },
    {
        name: "cobalt(III)",
        symbol: "Co",
        charge: 3,
        isPolyatomic: false,
    },
    {
        name: "gold(III)",
        symbol: "Au",
        charge: 3,
        isPolyatomic: false,
    },
    {
        name: "iron(III)",
        symbol: "Fe",
        charge: 3,
        isPolyatomic: false,
    },
    {
        name: "manganese(III)",
        symbol: "Mn",
        charge: 3,
        isPolyatomic: false,
    },
    {
        name: "nickel(III)",
        symbol: "Ni",
        charge: 3,
        isPolyatomic: false,
    },
    {
        name: "scandium(III)",
        symbol: "Sc",
        charge: 3,
        isPolyatomic: false,
    },
    {
        name: "vanadium(III)",
        symbol: "V",
        charge: 3,
        isPolyatomic: false,
    },
    {
        name: "lead(IV)",
        symbol: "Pb",
        charge: 4,
        isPolyatomic: false,
    },
    {
        name: "osmium(IV)",
        symbol: "Os",
        charge: 4,
        isPolyatomic: false,
    },
    {
        name: "palladium(IV)",
        symbol: "Pd",
        charge: 4,
        isPolyatomic: false,
    },
    {
        name: "platinum(IV)",
        symbol: "Pt",
        charge: 4,
        isPolyatomic: false,
    },
    {
        name: "tin(IV)",
        symbol: "Sn",
        charge: 4,
        isPolyatomic: false,
    },
    {
        name: "titanium(IV)",
        symbol: "Ti",
        charge: 4,
        isPolyatomic: false,
    },
    {
        name: "chromium(V)",
        symbol: "Cr",
        charge: 5,
        isPolyatomic: false,
    },
    {
        name: "manganese(V)",
        symbol: "Mn",
        charge: 5,
        isPolyatomic: false,
    },
    {
        name: "vanadium(V)",
        symbol: "V",
        charge: 5,
        isPolyatomic: false,
    },
    {
        name: "tungsten(V)",
        symbol: "W",
        charge: 5,
        isPolyatomic: false,
    },
    {
        name: "chromium(VI)",
        symbol: "Cr",
        charge: 6,
        isPolyatomic: false,
    },
    {
        name: "molybdenum(VI)",
        symbol: "Mo",
        charge: 6,
        isPolyatomic: false,
    },
    {
        name: "osmium(VI)",
        symbol: "Os",
        charge: 6,
        isPolyatomic: false,
    },
    {
        name: "ruthenium(VI)",
        symbol: "Ru",
        charge: 6,
        isPolyatomic: false,
    },
    {
        name: "manganese(VII)",
        symbol: "Mn",
        charge: 7,
        isPolyatomic: false,
    },
    {
        name: "rhenium(VII)",
        symbol: "Re",
        charge: 7,
        isPolyatomic: false,
    },
    {
        name: "osmium(VIII)",
        symbol: "Os",
        charge: 8,
        isPolyatomic: false,
    },
    {
        name: "ruthenium(VIII)",
        symbol: "Ru",
        charge: 8,
        isPolyatomic: false,
    },
]