import { Ion } from "../../interfaces"

export const transitionMetalCations: Ion[] = [
    {
        ionName: "copper(I)",
        ionSymbol: ["Cu"],
        charge: 1,
        isPolyatomic: false,
    },
    {
        ionName: "gold(I)",
        ionSymbol: ["Au"],
        charge: 1,
        isPolyatomic: false,
    },
    {
        ionName: "copper(II)",
        ionSymbol: ["Cu"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "cobalt(II)",
        ionSymbol: ["Co"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "iron(II)",
        ionSymbol: ["Fe"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "lead(II)",
        ionSymbol: ["Pb"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "mercury(II)",
        ionSymbol: ["Hg"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "nickel(II)",
        ionSymbol: ["Ni"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "platinum(II)",
        ionSymbol: ["Pt"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "tin(II)",
        ionSymbol: ["Sn"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "titanium(II)",
        ionSymbol: ["Ti"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "chromium(III)",
        ionSymbol: ["Cr"],
        charge: 2,
        isPolyatomic: false,
    },
    {
        ionName: "cobalt(III)",
        ionSymbol: ["Co"],
        charge: 3,
        isPolyatomic: false,
    },
    {
        ionName: "gold(III)",
        ionSymbol: ["Au"],
        charge: 3,
        isPolyatomic: false,
    },
    {
        ionName: "iron(III)",
        ionSymbol: ["Fe"],
        charge: 3,
        isPolyatomic: false,
    },
    {
        ionName: "manganese(III)",
        ionSymbol: ["Mn"],
        charge: 3,
        isPolyatomic: false,
    },
    {
        ionName: "nickel(III)",
        ionSymbol: ["Ni"],
        charge: 3,
        isPolyatomic: false,
    },
    {
        ionName: "scandium(III)",
        ionSymbol: ["Sc"],
        charge: 3,
        isPolyatomic: false,
    },
    {
        ionName: "vanadium(III)",
        ionSymbol: ["V"],
        charge: 3,
        isPolyatomic: false,
    },
    {
        ionName: "lead(IV)",
        ionSymbol: ["Pb"],
        charge: 4,
        isPolyatomic: false,
    },
    {
        ionName: "osmium(IV)",
        ionSymbol: ["Os"],
        charge: 4,
        isPolyatomic: false,
    },
    {
        ionName: "palladium(IV)",
        ionSymbol: ["Pd"],
        charge: 4,
        isPolyatomic: false,
    },
    {
        ionName: "platinum(IV)",
        ionSymbol: ["Pt"],
        charge: 4,
        isPolyatomic: false,
    },
    {
        ionName: "tin(IV)",
        ionSymbol: ["Sn"],
        charge: 4,
        isPolyatomic: false,
    },
    {
        ionName: "titanium(IV)",
        ionSymbol: ["Ti"],
        charge: 4,
        isPolyatomic: false,
    },
    {
        ionName: "chromium(V)",
        ionSymbol: ["Cr"],
        charge: 5,
        isPolyatomic: false,
    },
    {
        ionName: "manganese(V)",
        ionSymbol: ["Mn"],
        charge: 5,
        isPolyatomic: false,
    },
    {
        ionName: "vanadium(V)",
        ionSymbol: ["V"],
        charge: 5,
        isPolyatomic: false,
    },
    {
        ionName: "tungsten(V)",
        ionSymbol: ["W"],
        charge: 5,
        isPolyatomic: false,
    },
    {
        ionName: "chromium(VI)",
        ionSymbol: ["Cr"],
        charge: 6,
        isPolyatomic: false,
    },
    {
        ionName: "molybdenum(VI)",
        ionSymbol: ["Mo"],
        charge: 6,
        isPolyatomic: false,
    },
    {
        ionName: "osmium(VI)",
        ionSymbol: ["Os"],
        charge: 6,
        isPolyatomic: false,
    },
    {
        ionName: "ruthenium(VI)",
        ionSymbol: ["Ru"],
        charge: 6,
        isPolyatomic: false,
    },
    {
        ionName: "manganese(VII)",
        ionSymbol: ["Mn"],
        charge: 7,
        isPolyatomic: false,
    },
    {
        ionName: "rhenium(VII)",
        ionSymbol: ["Re"],
        charge: 7,
        isPolyatomic: false,
    },
    {
        ionName: "osmium(VIII)",
        ionSymbol: ["Os"],
        charge: 8,
        isPolyatomic: false,
    },
    {
        ionName: "ruthenium(VIII)",
        ionSymbol: ["Ru"],
        charge: 8,
        isPolyatomic: false,
    },
]